apiVersion: v1
kind: Pod
metadata:
  name: repro-pod
  labels:
    name: repro-pod
spec:
  containers:
  - name: repro-pod
    image: ubuntu
    command:
      - "/bin/sleep"
      - "10000"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
      - name: k8s-secret 
        mountPath: /mount/secrets
  volumes:
  - name: k8s-secret
    secret:
      secretName: repro
      optional: false