apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: repro
spec:
  image: "ttl.sh/spinapp-volume-repro:2h"
  executor: containerd-shim-spin
  replicas: 1
  volumeMounts:
    - name: k8s-secret
      mountPath: /mount/secrets
      readOnly: true
  volumes:
    - name: k8s-secret
      secret:
        secretName: repro
        optional: false
